### ISSUE TITLE
which is which?

### ISSUE THREAD

**Issue by lb42** [GutenbergSource/66829-Loos-Gentlemen-prefer-blondes#1]
There seem to be two TEI sources here: one in the file GentlemenPreferBlondes-1.0.tei and the other in the file 
Processed/GentlemenPreferBlondes.xml . Which is THE source?

**Comment by jhellingman** [comment]
The .tei file is my source file. This is however in a now obsolete SGML format (which I still prefer for manual editing); the .xml version is a direct translation of the same to XML. This is still in TEI P3 format, but can be further converted to P4 or P5 using the available tooling in XSLT.

PS. In some of the other projects here, I also use ASCII transcriptions of non Latin scripts; in the .xml version I translate these to Unicode.

**Comment by lb42** [comment]
Thanks for the quick response : I had figured out that the .xml file was probably the one to look at these days, though I am intrigued to learn that you are still editing in SGML!  It would surely be better to make available a TEI XML version  which is compatible with TEI P5, as TEI P4 ceased being supported by the TEI years and years ago...  I would be very pleased to provide some XSLT to do that if you like (I am not sure what you meant by "!available tooling" but I don't see any in the github repo) -- not least because this is one of my favourite books!

**Comment by jhellingman** [comment]
Hi Lou, I am aware of that. My legacy shows, since I started using TEI for ebooks in 1995 (using TeX to render them!). My home-grown tooling is in https://github.com/jhellingman/tei2html, and in that I've put Sebastian Rahtz' tei2tei and p4top5 xslt as well (with some additions), and can easily be used to get to P5. If you look a bit closer, you may notice I borrow later TEI constructs when I have a need for them. It is just that I have about 1000 texts in SGML, and as long as James Clark's nsgml keeps working, I can keep them as they are :-)

**Comment by lb42** [comment]
I had a quick scan through your wiki pages. You might want to update the link to the TEI migration page if that's how you expect people to convert your P4 to P5: it's now at https://www.tei-c.org/Vault/P4/migrate.html  -- as I said, the TEI withdrew all support for P4 back in 2015, I think. 
I tried converting the P4 version of "Gentlemen prefer blondes" using Sebastrians p4top5.xsl, which was mostly fine, though it did produce a couple of validation errors (there's no @rel attribute on `<tei:ref>`; and `<namespace>` requires a child `<tagUsage>`). 
More seriously I am puzzled by your use of what looks like a prefix convention for URLs e.g. facs="f:005" -- I assume this means that the "f:" prefix is to be mapped somehow to a place where I might find the corresponding page image. But I cannot see any place where that mapping is made explicit. 
But this is not really the place for such comments. I will just say how pleased I am to see that Gutenberg is at last starting to host TEI files. As you probably know there's some history behind that too...

**Comment by jhellingman** [comment]
Let me update those details in the other place. Not using the standard suite of tools allows me to be a little bit loose. Normally, when processing text that come from PG distributed proofreaders, I use de @facs attribute to point to the images in that system (using a prefixDef). The @rel was introduced by an entity in my scripts (will remove that). I will investigate what to do with the `<namespace>`, which is also not in my source. My perl scripts include an option to go to P5 (but Perl is another way I show my legacy!) Gutenberg is (sadly) not hosting TEI files, so I place them here in GitHub instead.

**Comment by jhellingman** [comment]
Fixed the @rel attribute and added a P5 xml version.
