### ISSUE TITLE
Image files

### ISSUE THREAD

**Issue by lb42** [GutenbergSource/66829-Loos-Gentlemen-prefer-blondes#4]
There are two sets of image files (images@1 and @images@2) : what is the difference between them?

**Comment by jhellingman** [comment]
images@1 are at a (nominal) 144 DPI (maximized at 720 px edge); images@2 are at a nominal 288 DPI and max 1440px edge. My normal processing will select one or the other, depending on configuration.

Note that the actual source of images doesn't provide a strictly correct DPI figure (as generated by a camera), and the quality of illustrations suffers a bit from Jpeg compression artifacts in that source.)
